# Generated by Django 2.2.2 on 2019-06-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='estrellas',
        ),
    ]
