# Generated by Django 2.2.2 on 2019-06-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_estrellas'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='estrellas',
            field=models.IntegerField(default=0),
        ),
    ]
