# Generated by Django 2.2.2 on 2019-06-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_habitaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pension', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Pension',
                'verbose_name_plural': 'Tipo Pensiones',
            },
        ),
        migrations.CreateModel(
            name='Precio_pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hotel_tipo_pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
                ('precio_tipo_pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Tipo_pension')),
            ],
            options={
                'verbose_name': 'Precio Pension',
                'verbose_name_plural': 'Precio Pensiones',
            },
        ),
    ]
