# Generated by Django 2.2.2 on 2019-06-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_precio_pension_tipo_pension'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='baños',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='garaje',
            field=models.IntegerField(default=0),
        ),
    ]
