# Generated by Django 2.2.2 on 2019-06-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20190619_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_alojamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('habitacion_tipo_alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Habitaciones')),
            ],
            options={
                'verbose_name': 'Tipo Alojamiento',
                'verbose_name_plural': 'Tipos Alojamientos',
            },
        ),
    ]
