# Generated by Django 2.2.2 on 2019-06-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_tipo_alojamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='camas',
            field=models.IntegerField(default=0),
        ),
    ]
