# Generated by Django 2.2.2 on 2019-06-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
