# Generated by Django 2.2.2 on 2019-06-22 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0010_habitaciones_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valoracion', models.IntegerField(default=0)),
                ('valoracion_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Reserva')),
                ('valoracion_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
            },
        ),
    ]
