# Generated by Django 2.2.2 on 2019-06-22 22:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_valoraciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Reservas_habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('ocupantes', models.IntegerField(default=0)),
                ('reserva_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Habitaciones')),
                ('reserva_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Reserva')),
            ],
            options={
                'verbose_name': 'Reserva habitacion',
                'verbose_name_plural': 'Reservas habitaciones',
            },
        ),
    ]
