# Generated by Django 2.2.2 on 2019-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20190622_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio_pension',
            name='precio',
            field=models.DecimalField(choices=[('Completa', 150.0), ('Media', 100.0), ('Desayuno', 60.0), ('Nada', 0.0)], decimal_places=2, max_digits=5),
        ),
    ]
