# Generated by Django 2.2.2 on 2019-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20190623_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio_pension',
            name='precio',
            field=models.DecimalField(choices=[(150.0, 150.0), (100.0, 100.0), (60.0, 60.0), (0.0, 0.0)], decimal_places=2, max_digits=5),
        ),
    ]
