# Generated by Django 2.2.2 on 2019-06-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20190623_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='precio',
        ),
        migrations.AlterField(
            model_name='tipo_pension',
            name='tipo_pension',
            field=models.CharField(choices=[('completa', 'completa'), ('media', 'media'), ('desayuno', 'desayuno'), ('nada', 'nada')], max_length=50),
        ),
    ]
