# Generated by Django 2.2.2 on 2019-06-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_auto_20190624_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_alojamiento',
            name='descripcion',
            field=models.CharField(choices=[('doble', 'doble'), ('individual', 'individual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tipo_alojamiento',
            name='precio',
            field=models.DecimalField(choices=[(200, 200), (100, 100)], decimal_places=2, max_digits=5),
        ),
    ]
